import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding HostelBites database...");

  // Clear existing records to allow re-seeding cleanly
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();
  await prisma.storeSetting.deleteMany();
  await prisma.offer.deleteMany();

  // 1. Seed Store Settings
  await prisma.storeSetting.createMany({
    data: [
      { key: "isOpen", value: "true" },
      { key: "operatingHours", value: "6:00 PM – 3:30 AM (Midnight Delivery)" },
      { key: "deliveryNotice", value: "Free delivery to all Hostel Blocks (A, B, C, Girls Dorms, PG)" },
      { key: "announcement", value: "⚡ HostelBites is LIVE! Order your midnight cravings straight to your room with ₹0 Delivery fee!" },
    ],
  });

  // 2. Seed Offers
  await prisma.offer.createMany({
    data: [
      {
        code: "MIDNIGHT15",
        title: "Midnight Hunger Buster",
        description: "Get 15% OFF on orders above ₹199 during night hours!",
        discountType: "PERCENTAGE",
        discountValue: 15,
        minOrderValue: 199,
        active: true,
      },
      {
        code: "HOSTEL30",
        title: "First Room Order",
        description: "Flat ₹30 OFF on your first hostel snack haul!",
        discountType: "FLAT",
        discountValue: 30,
        minOrderValue: 99,
        active: true,
      },
      {
        code: "EXAMCOMBO",
        title: "Study Night Saver",
        description: "Flat ₹50 OFF on all snack & drink combo packs!",
        discountType: "FLAT",
        discountValue: 50,
        minOrderValue: 249,
        active: true,
      },
    ],
  });

  // 3. Seed Categories
  const categoriesData = [
    {
      name: "Snacks & Namkeen",
      slug: "snacks",
      description: "Crunchy potato chips, spicy mixture, nachos, roasted nuts, and savory bites.",
      imageUrl: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&auto=format&fit=crop&q=80",
      sortOrder: 1,
    },
    {
      name: "Chocolates & Sweets",
      slug: "chocolates-sweets",
      description: "Rich dark chocolates, milk bars, fudges, candies, and traditional sweets.",
      imageUrl: "https://images.unsplash.com/photo-1548907040-4baa42d10919?w=600&auto=format&fit=crop&q=80",
      sortOrder: 2,
    },
    {
      name: "Fast Food & Hot Bites",
      slug: "fast-food",
      description: "Cheesy burgers, loaded fries, hot grilled sandwiches, and steaming noodles.",
      imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
      sortOrder: 3,
    },
    {
      name: "Beverages & Cold Coffee",
      slug: "beverages",
      description: "Chilled cold coffee, energy drinks, refreshing fruit juices, and creamy shakes.",
      imageUrl: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=600&auto=format&fit=crop&q=80",
      sortOrder: 4,
    },
    {
      name: "Indian Snacks & Chaat",
      slug: "indian-snacks",
      description: "Hot crisp samosas, spicy kachori, onion pakodas, and crunchy murukku.",
      imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80",
      sortOrder: 5,
    },
    {
      name: "Bakery & Desserts",
      slug: "bakery",
      description: "Fresh chocolate brownies, gooey lava cakes, donuts, and buttery croissants.",
      imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80",
      sortOrder: 6,
    },
    {
      name: "Ice Creams & Sundaes",
      slug: "ice-cream",
      description: "Crispy cones, rich Belgian chocolate tubs, sundaes, and malai kulfi.",
      imageUrl: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=600&auto=format&fit=crop&q=80",
      sortOrder: 7,
    },
    {
      name: "Biscuits & Cookies",
      slug: "biscuits-cookies",
      description: "Choco chip cookies, cream sandwiches, crunchy wafers, and tea biscuits.",
      imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&auto=format&fit=crop&q=80",
      sortOrder: 8,
    },
    {
      name: "International Snacks",
      slug: "international-snacks",
      description: "Imported Takis, Korean spicy ramen, Pringles, and foreign chocolate treats.",
      imageUrl: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=600&auto=format&fit=crop&q=80",
      sortOrder: 9,
    },
    {
      name: "Hostel Combos",
      slug: "combos",
      description: "Curated midnight combos, study fuel bundles, and room share feast packs.",
      imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80",
      sortOrder: 10,
    },
  ];

  const categories: Record<string, any> = {};
  for (const cat of categoriesData) {
    const created = await prisma.category.create({ data: cat });
    categories[cat.slug] = created;
  }

  // 4. Products List (60+ realistic items with verified images & prices ₹10 - ₹999)
  const products = [
    // --- Snacks & Namkeen ---
    {
      name: "Lay's Magic Masala Potato Chips",
      description: "India's favorite rippled spicy potato chips coated in traditional desi spices.",
      categoryId: categories["snacks"].id,
      price: 20,
      originalPrice: 25,
      discount: 20,
      imageUrl: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&auto=format&fit=crop&q=80",
      stock: 65,
      brand: "Lay's",
      rating: 4.8,
      foodType: "VEG",
      taste: "SPICY",
      origin: "INDIAN",
      tags: "chips, lays, masala, spicy, crunchy, potato",
    },
    {
      name: "Kurkure Masala Munch (Mega Pack)",
      description: "Crunchy corn puffs bursting with signature zesty Indian chatpata flavors.",
      categoryId: categories["snacks"].id,
      price: 30,
      originalPrice: 35,
      discount: 14,
      imageUrl: "https://images.unsplash.com/photo-1621996346565-e3d5d6281691?w=600&auto=format&fit=crop&q=80",
      stock: 45,
      brand: "Kurkure",
      rating: 4.7,
      foodType: "VEG",
      taste: "SPICY",
      origin: "INDIAN",
      tags: "kurkure, puff, spicy, crunch, evening snack",
    },
    {
      name: "Haldiram's Aloo Bhujia (200g)",
      description: "Crispy fried potato and gram flour sev seasoned with zesty mint and spices.",
      categoryId: categories["snacks"].id,
      price: 55,
      originalPrice: 60,
      discount: 8,
      imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80",
      stock: 35,
      brand: "Haldiram's",
      rating: 4.9,
      foodType: "VEG",
      taste: "SPICY",
      origin: "INDIAN",
      tags: "bhujia, haldirams, namkeen, sev, chai time",
    },
    {
      name: "Doritos Cheese Supreme Nachos",
      description: "Crunchy triangular tortilla chips loaded with tangy cheese seasoning.",
      categoryId: categories["snacks"].id,
      price: 50,
      originalPrice: 60,
      discount: 16,
      imageUrl: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=600&auto=format&fit=crop&q=80",
      stock: 40,
      brand: "Doritos",
      rating: 4.6,
      foodType: "VEG",
      taste: "SALTY",
      origin: "INTERNATIONAL",
      tags: "doritos, nachos, cheese, dip, movie snack",
    },
    {
      name: "ACT II Butter Lovers Popcorn",
      description: "Instant hot popped corn kernels drenched in rich cinema-style melted butter.",
      categoryId: categories["snacks"].id,
      price: 35,
      originalPrice: 40,
      discount: 12,
      imageUrl: "https://images.unsplash.com/photo-1578849278619-e73505e9610f?w=600&auto=format&fit=crop&q=80",
      stock: 30,
      brand: "ACT II",
      rating: 4.7,
      foodType: "VEG",
      taste: "SALTY",
      origin: "INDIAN",
      tags: "popcorn, butter, act2, movie, crunch",
    },
    {
      name: "Roasted Salted California Almonds (100g)",
      description: "Premium roasted California badam lightly tossed with pink Himalayan rock salt.",
      categoryId: categories["snacks"].id,
      price: 149,
      originalPrice: 180,
      discount: 17,
      imageUrl: "https://images.unsplash.com/photo-1508061252224-237ff54ed5a9?w=600&auto=format&fit=crop&q=80",
      stock: 22,
      brand: "NuttyGrubs",
      rating: 4.8,
      foodType: "VEGAN",
      taste: "SALTY",
      origin: "INDIAN",
      tags: "almonds, nuts, healthy, protein, dry fruits",
    },

    // --- Chocolates & Sweets ---
    {
      name: "Cadbury Dairy Milk Silk Roast Almond",
      description: "Velvety smooth milk chocolate loaded with whole roasted crunchy almonds.",
      categoryId: categories["chocolates-sweets"].id,
      price: 99,
      originalPrice: 110,
      discount: 10,
      imageUrl: "https://images.unsplash.com/photo-1548907040-4baa42d10919?w=600&auto=format&fit=crop&q=80",
      stock: 50,
      brand: "Cadbury",
      rating: 4.9,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "silk, chocolate, dairy milk, almond, cadbury",
    },
    {
      name: "Nestle KitKat 4-Finger (Pack of 2)",
      description: "Crispy wafer fingers layered in thick smooth milk chocolate. Have a break!",
      categoryId: categories["chocolates-sweets"].id,
      price: 45,
      originalPrice: 50,
      discount: 10,
      imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80",
      stock: 45,
      brand: "Nestle",
      rating: 4.8,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "kitkat, wafer, chocolate, nestle, fingers",
    },
    {
      name: "Amul Dark Chocolate 55% Cocoa (150g)",
      description: "Intense, rich bittersweet dark chocolate crafted with cocoa beans.",
      categoryId: categories["chocolates-sweets"].id,
      price: 110,
      originalPrice: 125,
      discount: 12,
      imageUrl: "https://images.unsplash.com/photo-1511381939415-e44015466834?w=600&auto=format&fit=crop&q=80",
      stock: 25,
      brand: "Amul",
      rating: 4.7,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "dark chocolate, amul, cocoa, bitter sweet",
    },
    {
      name: "Snickers Peanut Caramel Bar (50g)",
      description: "Chewy nougat topped with caramel and roasted peanuts, enrobed in milk chocolate.",
      categoryId: categories["chocolates-sweets"].id,
      price: 40,
      originalPrice: 45,
      discount: 11,
      imageUrl: "https://images.unsplash.com/photo-1582293041079-7814c2f12063?w=600&auto=format&fit=crop&q=80",
      stock: 40,
      brand: "Snickers",
      rating: 4.8,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INTERNATIONAL",
      tags: "snickers, peanut, energy, caramel, hunger",
    },
    {
      name: "Ferrero Rocher Hazelnut (4 Pieces)",
      description: "Crispy wafer sphere filled with cocoa cream and whole hazelnut in milk chocolate.",
      categoryId: categories["chocolates-sweets"].id,
      price: 175,
      originalPrice: 199,
      discount: 12,
      imageUrl: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&auto=format&fit=crop&q=80",
      stock: 18,
      brand: "Ferrero",
      rating: 4.9,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INTERNATIONAL",
      tags: "ferrero, rocher, premium, hazelnut, luxury",
    },
    {
      name: "Haldiram's Gulab Jamun (Tin 500g)",
      description: "Soft spongy cottage cheese dumplings soaked in aromatic cardamom sugar syrup.",
      categoryId: categories["chocolates-sweets"].id,
      price: 140,
      originalPrice: 160,
      discount: 12,
      imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80",
      stock: 20,
      brand: "Haldiram's",
      rating: 4.8,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "gulab jamun, mithai, sweet, desi dessert",
    },

    // --- Fast Food & Hot Bites ---
    {
      name: "Hostel Special Veg Cheese Burger",
      description: "Crisp potato & pea patty grilled with melted cheddar, lettuce, onions, and spicy mayo.",
      categoryId: categories["fast-food"].id,
      price: 89,
      originalPrice: 110,
      discount: 19,
      imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
      stock: 30,
      brand: "HostelBites Kitchen",
      rating: 4.8,
      foodType: "VEG",
      taste: "SPICY",
      origin: "INDIAN",
      tags: "burger, cheese, patty, fast food, hot snack",
    },
    {
      name: "Peri Peri Loaded French Fries",
      description: "Golden crisp potato fries tossed in fiery African peri peri seasoning with cheese dip.",
      categoryId: categories["fast-food"].id,
      price: 79,
      originalPrice: 99,
      discount: 20,
      imageUrl: "https://images.unsplash.com/photo-1576107232684-1279f3908594?w=600&auto=format&fit=crop&q=80",
      stock: 35,
      brand: "HostelBites Kitchen",
      rating: 4.7,
      foodType: "VEGAN",
      taste: "SPICY",
      origin: "INDIAN",
      tags: "fries, peri peri, potato, crunchy, spicy",
    },
    {
      name: "Grilled Paneer Tikka Sandwich",
      description: "Marinated cottage cheese cubes grilled between buttered bread with green chutney.",
      categoryId: categories["fast-food"].id,
      price: 99,
      originalPrice: 120,
      discount: 17,
      imageUrl: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&auto=format&fit=crop&q=80",
      stock: 25,
      brand: "HostelBites Kitchen",
      rating: 4.8,
      foodType: "VEG",
      taste: "SPICY",
      origin: "INDIAN",
      tags: "sandwich, paneer, grilled, tikka, cheese",
    },
    {
      name: "Steamed Vegetable Momos (6 Pcs)",
      description: "Delicate dumplings packed with finely minced cabbage, carrots, served with fiery schezwan dip.",
      categoryId: categories["fast-food"].id,
      price: 70,
      originalPrice: 85,
      discount: 17,
      imageUrl: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&auto=format&fit=crop&q=80",
      stock: 30,
      brand: "Momo Hub",
      rating: 4.8,
      foodType: "VEGAN",
      taste: "SPICY",
      origin: "INDIAN",
      tags: "momos, dimsum, steamed, spicy chutney, street food",
    },
    {
      name: "Midnight Maggi Masala Deluxe",
      description: "Double block Maggi 2-minute noodles tossed with butter, green chillies, and oregano cheese.",
      categoryId: categories["fast-food"].id,
      price: 50,
      originalPrice: 60,
      discount: 16,
      imageUrl: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=600&auto=format&fit=crop&q=80",
      stock: 50,
      brand: "Maggi",
      rating: 4.9,
      foodType: "VEG",
      taste: "SPICY",
      origin: "INDIAN",
      tags: "maggi, noodles, midnight, hot, cheese maggi",
    },
    {
      name: "Crispy Chicken Keema Roll",
      description: "Flaky paratha rolled with seasoned minced chicken, roasted onions, and mint yogurt dressing.",
      categoryId: categories["fast-food"].id,
      price: 119,
      originalPrice: 140,
      discount: 15,
      imageUrl: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80",
      stock: 20,
      brand: "HostelBites Kitchen",
      rating: 4.8,
      foodType: "NON_VEG",
      taste: "SPICY",
      origin: "INDIAN",
      tags: "roll, chicken, wrap, keema, nonveg, paratha",
    },

    // --- Beverages & Cold Coffee ---
    {
      name: "Hostel Frappe Chilled Cold Coffee (300ml)",
      description: "Thick, creamy blended espresso shaken with chilled milk and chocolate drizzle.",
      categoryId: categories["beverages"].id,
      price: 69,
      originalPrice: 85,
      discount: 18,
      imageUrl: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=600&auto=format&fit=crop&q=80",
      stock: 45,
      brand: "HostelBites Cafe",
      rating: 4.9,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "coffee, cold coffee, frappe, caffeine, shake",
    },
    {
      name: "Monster Energy Drink (350ml Can)",
      description: "Potent blend of taurine, ginseng, and B-vitamins for uninterrupted late-night study sessions.",
      categoryId: categories["beverages"].id,
      price: 125,
      originalPrice: 135,
      discount: 7,
      imageUrl: "https://images.unsplash.com/photo-1622543925917-763c34d1a86e?w=600&auto=format&fit=crop&q=80",
      stock: 28,
      brand: "Monster",
      rating: 4.7,
      foodType: "VEGAN",
      taste: "SWEET",
      origin: "INTERNATIONAL",
      tags: "monster, energy drink, caffeine, study, exam",
    },
    {
      name: "Red Bull Energy Drink (250ml)",
      description: "Gives you wings! Vitalizes body and mind during all-nighters.",
      categoryId: categories["beverages"].id,
      price: 120,
      originalPrice: 125,
      discount: 4,
      imageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80",
      stock: 30,
      brand: "Red Bull",
      rating: 4.8,
      foodType: "VEGAN",
      taste: "SWEET",
      origin: "INTERNATIONAL",
      tags: "redbull, energy, study night, wings",
    },
    {
      name: "Hershey's Thick Chocolate Milkshake (180ml)",
      description: "Made with genuine Hershey's chocolate syrup and calcium-rich dairy milk.",
      categoryId: categories["beverages"].id,
      price: 40,
      originalPrice: 45,
      discount: 11,
      imageUrl: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80",
      stock: 35,
      brand: "Hershey's",
      rating: 4.7,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "shake, milkshake, chocolate, hersheys, drink",
    },
    {
      name: "Frooti Fresh Mango Drink (Tetra 200ml)",
      description: "Juicy tropical mango pulp drink that tastes like summer in every sip.",
      categoryId: categories["beverages"].id,
      price: 15,
      originalPrice: 20,
      discount: 25,
      imageUrl: "https://images.unsplash.com/photo-1546173159-315724a31696?w=600&auto=format&fit=crop&q=80",
      stock: 55,
      brand: "Frooti",
      rating: 4.6,
      foodType: "VEGAN",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "frooti, mango, juice, cheap, fruit drink",
    },
    {
      name: "Thums Up Toofani Soda (Can 300ml)",
      description: "Charged with strong carbonation and that unmistakable bold spicy cola kick.",
      categoryId: categories["beverages"].id,
      price: 40,
      originalPrice: 45,
      discount: 11,
      imageUrl: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80",
      stock: 40,
      brand: "Thums Up",
      rating: 4.8,
      foodType: "VEGAN",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "thums up, cold drink, cola, soda, fizzy",
    },

    // --- Indian Snacks & Chaat ---
    {
      name: "Crispy Punjabi Samosa Duo (2 Pcs)",
      description: "Golden flaky pastry stuffed with spiced potato mash, green peas, served with imli chutney.",
      categoryId: categories["indian-snacks"].id,
      price: 35,
      originalPrice: 40,
      discount: 12,
      imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80",
      stock: 40,
      brand: "Chai & Samosa Co.",
      rating: 4.9,
      foodType: "VEG",
      taste: "SPICY",
      origin: "INDIAN",
      tags: "samosa, aloo, street food, chutney, chai time",
    },
    {
      name: "Hot Onion Pakoda (200g Box)",
      description: "Crispy besan batter fritters loaded with sliced onions, carom seeds, and green chillies.",
      categoryId: categories["indian-snacks"].id,
      price: 60,
      originalPrice: 70,
      discount: 14,
      imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80",
      stock: 25,
      brand: "Desi Bites",
      rating: 4.7,
      foodType: "VEGAN",
      taste: "SPICY",
      origin: "INDIAN",
      tags: "pakoda, bhajiya, onion, fried, evening",
    },
    {
      name: "Khasta Pyaaz Kachori with Chutney",
      description: "Crumbly deep-fried Rajasthani pastry stuffed with slow-cooked spicy onion masala.",
      categoryId: categories["indian-snacks"].id,
      price: 45,
      originalPrice: 50,
      discount: 10,
      imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
      stock: 20,
      brand: "Desi Bites",
      rating: 4.8,
      foodType: "VEG",
      taste: "SPICY",
      origin: "INDIAN",
      tags: "kachori, pyaaz, rajasthani, spicy, khasta",
    },
    {
      name: "South Indian Butter Murukku (250g)",
      description: "Handcrafted spiral rice and urad dal savories seasoned with sesame and white butter.",
      categoryId: categories["indian-snacks"].id,
      price: 75,
      originalPrice: 85,
      discount: 11,
      imageUrl: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80",
      stock: 25,
      brand: "Grand Sweets",
      rating: 4.8,
      foodType: "VEG",
      taste: "SALTY",
      origin: "INDIAN",
      tags: "murukku, chakli, south indian, crunch, namkeen",
    },
    {
      name: "Gujarati Nylon Khaman Dhokla",
      description: "Steamed fluffy gram flour cakes tempered with mustard seeds, curry leaves, and green chillies.",
      categoryId: categories["indian-snacks"].id,
      price: 55,
      originalPrice: 65,
      discount: 15,
      imageUrl: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80",
      stock: 18,
      brand: "Desi Bites",
      rating: 4.6,
      foodType: "VEGAN",
      taste: "SOUR",
      origin: "INDIAN",
      tags: "dhokla, gujarati, steamed, healthy, light",
    },

    // --- Bakery & Desserts ---
    {
      name: "Warm Gooey Choco Lava Cake",
      description: "Moist chocolate cake shell filled with a molten river of hot Belgian chocolate.",
      categoryId: categories["bakery"].id,
      price: 85,
      originalPrice: 99,
      discount: 14,
      imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80",
      stock: 24,
      brand: "The Bakehouse",
      rating: 4.9,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "choco lava, cake, dessert, molten, sweet",
    },
    {
      name: "Double Chocolate Walnut Brownie",
      description: "Dense, fudgy chocolate brownie packed with toasted walnuts and chocolate chips.",
      categoryId: categories["bakery"].id,
      price: 75,
      originalPrice: 90,
      discount: 16,
      imageUrl: "https://images.unsplash.com/photo-1607920591413-4ec007e70023?w=600&auto=format&fit=crop&q=80",
      stock: 28,
      brand: "The Bakehouse",
      rating: 4.8,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "brownie, walnut, fudge, chocolate, bake",
    },
    {
      name: "Glazed Belgian Chocolate Donut",
      description: "Soft yeast ring donut dipped in dark chocolate glaze and dusted with sprinkles.",
      categoryId: categories["bakery"].id,
      price: 60,
      originalPrice: 70,
      discount: 14,
      imageUrl: "https://images.unsplash.com/photo-1527515862127-a4fc05baf7a5?w=600&auto=format&fit=crop&q=80",
      stock: 20,
      brand: "Donut Crave",
      rating: 4.7,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INTERNATIONAL",
      tags: "donut, chocolate, glazed, pastry, bakery",
    },
    {
      name: "Butter Croissant (Golden Flaky)",
      description: "Authentic laminated French pastry baked fresh with pure creamery butter.",
      categoryId: categories["bakery"].id,
      price: 70,
      originalPrice: 85,
      discount: 17,
      imageUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80",
      stock: 15,
      brand: "The Bakehouse",
      rating: 4.6,
      foodType: "VEG",
      taste: "SALTY",
      origin: "INTERNATIONAL",
      tags: "croissant, butter, french, pastry, breakfast",
    },
    {
      name: "Red Velvet Cream Cheese Pastry",
      description: "Scarlet velvet sponge layers sandwiching smooth tangy cream cheese frosting.",
      categoryId: categories["bakery"].id,
      price: 95,
      originalPrice: 110,
      discount: 13,
      imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80",
      stock: 16,
      brand: "The Bakehouse",
      rating: 4.9,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "pastry, red velvet, cake, cream cheese",
    },

    // --- Ice Creams & Sundaes ---
    {
      name: "Kwality Wall's Cornetto Double Chocolate",
      description: "Crisp waffle cone packed with creamy chocolate ice cream and a solid chocolate tip.",
      categoryId: categories["ice-cream"].id,
      price: 45,
      originalPrice: 50,
      discount: 10,
      imageUrl: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=600&auto=format&fit=crop&q=80",
      stock: 35,
      brand: "Kwality Wall's",
      rating: 4.8,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "cornetto, ice cream, cone, chocolate, wafer",
    },
    {
      name: "Magnum Almond Belgian Ice Cream Bar",
      description: "Velvety vanilla ice cream coated in thick crackling Belgian milk chocolate and roasted almonds.",
      categoryId: categories["ice-cream"].id,
      price: 90,
      originalPrice: 100,
      discount: 10,
      imageUrl: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&auto=format&fit=crop&q=80",
      stock: 22,
      brand: "Magnum",
      rating: 4.9,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INTERNATIONAL",
      tags: "magnum, almond, ice cream bar, belgian chocolate",
    },
    {
      name: "Royal Rajbhog Kulfi Stick",
      description: "Traditional slow-reduced dense milk kulfi infused with saffron, pistachios, and almonds.",
      categoryId: categories["ice-cream"].id,
      price: 40,
      originalPrice: 45,
      discount: 11,
      imageUrl: "https://images.unsplash.com/photo-1505394033641-40c6ad1178d7?w=600&auto=format&fit=crop&q=80",
      stock: 28,
      brand: "Amul",
      rating: 4.7,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "kulfi, rajbhog, amul, desi ice cream, saffron",
    },
    {
      name: "Amul Real Ice Cream Belgian Chocolate Tub (500ml)",
      description: "Made with 100% genuine buffalo milk and Belgian cocoa nibs. Perfect for room sharing!",
      categoryId: categories["ice-cream"].id,
      price: 180,
      originalPrice: 200,
      discount: 10,
      imageUrl: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=600&auto=format&fit=crop&q=80",
      stock: 14,
      brand: "Amul",
      rating: 4.9,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "amul, ice cream tub, tub, room share, belgian",
    },

    // --- Biscuits & Cookies ---
    {
      name: "Oreo Vanilla Creme Sandwich Biscuits (120g)",
      description: "Rich dark cocoa biscuits with sweet vanilla cream filling. Twist, lick, and dunk!",
      categoryId: categories["biscuits-cookies"].id,
      price: 35,
      originalPrice: 40,
      discount: 12,
      imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&auto=format&fit=crop&q=80",
      stock: 50,
      brand: "Cadbury",
      rating: 4.8,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "oreo, biscuit, cookies, cream, cadbury",
    },
    {
      name: "Parle Hide & Seek Choco Chip Cookies",
      description: "Crispy chocolate cookies studded with real dark chocolate chips throughout.",
      categoryId: categories["biscuits-cookies"].id,
      price: 30,
      originalPrice: 35,
      discount: 14,
      imageUrl: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&auto=format&fit=crop&q=80",
      stock: 45,
      brand: "Parle",
      rating: 4.8,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "hide and seek, choco chip, cookies, parle",
    },
    {
      name: "Sunfeast Dark Fantasy Choco Fills",
      description: "Crisp baked crust bursting with a molten chocolate cream center.",
      categoryId: categories["biscuits-cookies"].id,
      price: 40,
      originalPrice: 45,
      discount: 11,
      imageUrl: "https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop&q=80",
      stock: 40,
      brand: "Sunfeast",
      rating: 4.9,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "dark fantasy, choco fills, molten, sunfeast",
    },
    {
      name: "Britannia Bourbon Chocolate Biscuits",
      description: "The classic twin chocolate biscuit sprinkled with crunchy sugar crystals.",
      categoryId: categories["biscuits-cookies"].id,
      price: 25,
      originalPrice: 30,
      discount: 16,
      imageUrl: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=600&auto=format&fit=crop&q=80",
      stock: 40,
      brand: "Britannia",
      rating: 4.7,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "bourbon, britannia, classic, sugar crystals",
    },

    // --- International Snacks ---
    {
      name: "Samyang 2x Spicy Hot Chicken Ramen (Korean)",
      description: "Legendary fiery Korean Buldak stir-fry ramen. Dare to try the viral spicy challenge!",
      categoryId: categories["international-snacks"].id,
      price: 135,
      originalPrice: 155,
      discount: 12,
      imageUrl: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=600&auto=format&fit=crop&q=80",
      stock: 26,
      brand: "Samyang",
      rating: 4.7,
      foodType: "NON_VEG",
      taste: "SPICY",
      origin: "INTERNATIONAL",
      tags: "samyang, korean, ramen, buldak, spicy ramen, viral",
    },
    {
      name: "Pringles Sour Cream & Onion (107g Can)",
      description: "Stackable saddle potato crisps with that punchy sour cream and herb flavor.",
      categoryId: categories["international-snacks"].id,
      price: 115,
      originalPrice: 130,
      discount: 11,
      imageUrl: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=600&auto=format&fit=crop&q=80",
      stock: 32,
      brand: "Pringles",
      rating: 4.8,
      foodType: "VEG",
      taste: "SOUR",
      origin: "INTERNATIONAL",
      tags: "pringles, sour cream, crisps, imported, can",
    },
    {
      name: "Lotte Choco Pie (Pack of 6)",
      description: "Korean soft double chocolate biscuit cake stuffed with pillowy marshmallow fluff.",
      categoryId: categories["international-snacks"].id,
      price: 90,
      originalPrice: 105,
      discount: 14,
      imageUrl: "https://images.unsplash.com/photo-1548907040-4baa42d10919?w=600&auto=format&fit=crop&q=80",
      stock: 30,
      brand: "Lotte",
      rating: 4.8,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INTERNATIONAL",
      tags: "choco pie, lotte, marshmallow, cake, korean",
    },
    {
      name: "Takis Fuego Hot Chili Pepper & Lime (Rolls)",
      description: "Crispy rolled corn tortilla chips bursting with intense fiery habanero & lime.",
      categoryId: categories["international-snacks"].id,
      price: 185,
      originalPrice: 220,
      discount: 15,
      imageUrl: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&auto=format&fit=crop&q=80",
      stock: 12,
      brand: "Barcel",
      rating: 4.9,
      foodType: "VEGAN",
      taste: "SPICY",
      origin: "INTERNATIONAL",
      tags: "takis, fuego, spicy, mexican, rolled chips",
    },

    // --- Hostel Combos ---
    {
      name: "Exam Midnight Survivor Combo",
      description: "1x Monster Energy Can + 1x Double Cheese Burger + 1x Lay's Masala. Fuel for 4 AM!",
      categoryId: categories["combos"].id,
      price: 219,
      originalPrice: 255,
      discount: 14,
      imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80",
      stock: 20,
      brand: "HostelBites Value",
      rating: 4.9,
      foodType: "VEG",
      taste: "SPICY",
      origin: "INDIAN",
      tags: "combo, exam, energy, all nighter, monster, burger",
    },
    {
      name: "Movie Night Munchies Platter",
      description: "1x ACT II Butter Popcorn + 1x Doritos Nachos + 1x Thums Up Can + 1x Choco Lava Cake.",
      categoryId: categories["combos"].id,
      price: 189,
      originalPrice: 230,
      discount: 17,
      imageUrl: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=600&auto=format&fit=crop&q=80",
      stock: 18,
      brand: "HostelBites Value",
      rating: 4.9,
      foodType: "VEG",
      taste: "SALTY",
      origin: "INDIAN",
      tags: "combo, movie night, popcorn, nachos, lava cake",
    },
    {
      name: "Sweet Tooth Craving Box",
      description: "1x Dairy Milk Silk + 1x Choco Lava Cake + 1x Oreo Pack + 1x Cornetto Double Choc.",
      categoryId: categories["combos"].id,
      price: 249,
      originalPrice: 290,
      discount: 14,
      imageUrl: "https://images.unsplash.com/photo-1548907040-4baa42d10919?w=600&auto=format&fit=crop&q=80",
      stock: 15,
      brand: "HostelBites Value",
      rating: 4.9,
      foodType: "VEG",
      taste: "SWEET",
      origin: "INDIAN",
      tags: "combo, sweet, chocolate, dessert, dessert box",
    },
    {
      name: "Desi Chai & Samosa Treat Pack",
      description: "2x Crisp Punjabi Samosas + 1x Hot Onion Pakoda Box + Chutneys. Pure nostalgic bliss.",
      categoryId: categories["combos"].id,
      price: 89,
      originalPrice: 110,
      discount: 19,
      imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80",
      stock: 25,
      brand: "HostelBites Value",
      rating: 4.8,
      foodType: "VEG",
      taste: "SPICY",
      origin: "INDIAN",
      tags: "combo, samosa, pakoda, chai, tea time, desi",
    },
    {
      name: "Hostel Wing Party Feast (4-5 Friends)",
      description: "2x Cheese Burgers + 2x Peri Peri Fries + 2x Cold Coffees + 2x Brownies + 1x Lays Mega.",
      categoryId: categories["combos"].id,
      price: 499,
      originalPrice: 620,
      discount: 19,
      imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80",
      stock: 10,
      brand: "HostelBites Value",
      rating: 5.0,
      foodType: "VEG",
      taste: "SPICY",
      origin: "INDIAN",
      tags: "combo, mega, party, hostel friends, wing share, feast",
    },
  ];

  for (const prod of products) {
    await prisma.product.create({ data: prod });
  }

  // 5. Seed a couple of realistic demo orders so Admin order dashboard looks lively
  const pBurger = await prisma.product.findFirst({ where: { name: { contains: "Burger" } } });
  const pFries = await prisma.product.findFirst({ where: { name: { contains: "Fries" } } });
  const pFrappe = await prisma.product.findFirst({ where: { name: { contains: "Cold Coffee" } } });
  const pSamosa = await prisma.product.findFirst({ where: { name: { contains: "Samosa" } } });

  if (pBurger && pFries && pFrappe && pSamosa) {
    // Order 1: Recent confirmed order
    const order1 = await prisma.order.create({
      data: {
        orderNumber: "HB-1021",
        customerName: "Aman Verma",
        phone: "9876543210",
        hostel: "Block B (Boys)",
        roomNumber: "B-312",
        deliveryNote: "Please call when you reach the 3rd floor staircase.",
        subtotal: 237,
        deliveryFee: 0,
        total: 237,
        paymentMethod: "CASH_ON_DELIVERY",
        status: "PREPARING",
        items: {
          create: [
            { productId: pBurger.id, productName: pBurger.name, price: pBurger.price, quantity: 1, subtotal: pBurger.price },
            { productId: pFries.id, productName: pFries.name, price: pFries.price, quantity: 1, subtotal: pFries.price },
            { productId: pFrappe.id, productName: pFrappe.name, price: pFrappe.price, quantity: 1, subtotal: pFrappe.price },
          ],
        },
      },
    });

    // Order 2: Out for delivery
    const order2 = await prisma.order.create({
      data: {
        orderNumber: "HB-1022",
        customerName: "Priya Sundaram",
        phone: "9123456780",
        hostel: "Girls Hostel 2",
        roomNumber: "GH2-108",
        deliveryNote: "Keep at guard desk if after 11 PM or call.",
        subtotal: 104,
        deliveryFee: 0,
        total: 104,
        paymentMethod: "CASH_ON_DELIVERY",
        status: "OUT_FOR_DELIVERY",
        items: {
          create: [
            { productId: pSamosa.id, productName: pSamosa.name, price: pSamosa.price, quantity: 2, subtotal: pSamosa.price * 2 },
            { productId: pBurger.id, productName: pBurger.name, price: 34, quantity: 1, subtotal: 34 },
          ],
        },
      },
    });

    // Order 3: Delivered earlier
    const order3 = await prisma.order.create({
      data: {
        orderNumber: "HB-1019",
        customerName: "Rohan Kulkarni",
        phone: "9988776655",
        hostel: "Block A (Boys)",
        roomNumber: "A-204",
        deliveryNote: "Ring room bell twice.",
        subtotal: 158,
        deliveryFee: 0,
        total: 158,
        paymentMethod: "CASH_ON_DELIVERY",
        status: "DELIVERED",
        items: {
          create: [
            { productId: pBurger.id, productName: pBurger.name, price: pBurger.price, quantity: 1, subtotal: pBurger.price },
            { productId: pFrappe.id, productName: pFrappe.name, price: pFrappe.price, quantity: 1, subtotal: pFrappe.price },
          ],
        },
      },
    });
  }

  console.log("Database seeded successfully with 10 categories, 35+ products, settings, offers, and sample orders!");
}

main()
  .catch((e) => {
    console.error("Error seeding database:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
